'use client';

/**
 * Client-side Mermaid renderer with a GUARANTEED fallback.
 *
 * We render `mermaid.render` inside an effect. If mermaid is unavailable, fails
 * to parse, or throws for any reason, we fall back to showing the raw source in
 * a <pre> with a copy button. A broken diagram must NEVER crash the page — the
 * whole render is wrapped so any throw is caught and downgraded to the source
 * view (see acceptance criterion #3).
 *
 * Mermaid is imported dynamically so it never runs on the server and never
 * bloats the initial route bundle.
 */

import { useEffect, useId, useRef, useState } from 'react';
import { CopyButton } from './copy-button';

type Status = 'loading' | 'ok' | 'fallback';

export function MermaidDiagram({ source }: { source: string }) {
  const [status, setStatus] = useState<Status>('loading');
  const [svg, setSvg] = useState<string>('');
  const rawId = useId();
  // Mermaid needs a DOM-id-safe string.
  const renderId = `mermaid-${rawId.replace(/[^a-zA-Z0-9]/g, '')}`;
  const mounted = useRef(true);

  useEffect(() => {
    mounted.current = true;

    (async () => {
      try {
        const mermaid = (await import('mermaid')).default;
        mermaid.initialize({
          startOnLoad: false,
          securityLevel: 'strict',
          theme: 'neutral',
        });
        // `render` both parses and produces SVG; it throws on a bad diagram.
        const { svg: rendered } = await mermaid.render(renderId, source);
        if (!mounted.current) return;
        setSvg(rendered);
        setStatus('ok');
      } catch {
        // Any failure (bad syntax, load error) → source fallback. No crash.
        if (!mounted.current) return;
        setStatus('fallback');
      }
    })();

    return () => {
      mounted.current = false;
    };
  }, [source, renderId]);

  if (status === 'ok') {
    return (
      <div className="flex flex-col gap-2">
        <div
          className="overflow-x-auto rounded-lg border bg-white p-4 [&_svg]:mx-auto [&_svg]:h-auto [&_svg]:max-w-full"
          // Mermaid output is generated by us from our own source with
          // securityLevel:'strict'; it is not user-authored HTML.
          dangerouslySetInnerHTML={{ __html: svg }}
        />
        <div className="flex justify-end">
          <CopyButton value={source} label="Copy diagram source" />
        </div>
      </div>
    );
  }

  if (status === 'loading') {
    return (
      <div className="flex h-40 items-center justify-center rounded-lg border bg-muted/20 text-sm text-muted-foreground">
        Rendering diagram…
      </div>
    );
  }

  // fallback
  return (
    <div className="flex flex-col gap-2">
      <p className="text-sm text-muted-foreground">
        The diagram could not be rendered. Here is the Mermaid source — paste it into any Mermaid
        viewer.
      </p>
      <div className="relative rounded-lg border bg-muted/30">
        <pre className="overflow-x-auto p-4 text-xs leading-relaxed">
          <code>{source}</code>
        </pre>
        <div className="absolute right-2 top-2">
          <CopyButton value={source} label="Copy source" />
        </div>
      </div>
    </div>
  );
}
